### ISSUE TITLE
add config for idp with self signed tls cert

### ISSUE THREAD

**Issue by hofmannmich** [Brainnwave/jwt-middleware#17]
Hi,
I want to use your traefik-plugin, but my IDP has a self signed TLS cert. So when I´ve done the configuration I see this error in the Traefik log (real host name changed to <my-host>):
{"plugin":"plugin-jwt","module":"github.com/Brainnwave/jwt-middleware","runtime":"","time":"2024-03-19T09:50:57Z","caller":"log/log.go:245","level":"error","message":"failed to fetch keys for https://<my-host>/: Get \"https://<my-host>/.well-known/openid-configuration\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
{"plugin":"plugin-jwt","module":"github.com/Brainnwave/jwt-middleware","runtime":"","time":"2024-03-19T09:50:57Z","caller":"log/log.go:245","level":"error","message":"key 7k92BcweutKe2P3WrGWW5omlAeR3IF8UKvNGKXjxSGw: fetched and no match"}

Can you add a config where I can deactivate TLS check? like insecureSkipVerify: true which is also possible in Traefik serversTransports config-element.

Thanks in advance.
Michael

**Comment by agilezebra** [comment]
Hi Michael. I've added https://github.com/Brainnwave/jwt-middleware/pull/18 . Let me know if it meets your needs and I'll merge. I opted to go for an explicit list of domains to use insecureSkipVerify on rather than a blanket option. Seems sensible but perhaps I missed some use case.

**Comment by hofmannmich** [comment]
Hi Graham, thanks for such a quick reaction. Looks good for me. If you merge I will use it asap. Thanks again.
