### ISSUE TITLE
Add support for GRPC requests, and respond with a GRPC compatible error code if so

### ISSUE THREAD

**Issue by cmartell-at-ocp** [Brainnwave/jwt-middleware#22]
Hello,

I've been using the middleware no problem but I'd love to see support for GRPC error responses if the original request was of content-type: application/grpc*.

I put together a basic PR #21 for now, and seems to work well in my environment (responding correctly depending on the content-type header.

**Comment by cmartell-at-ocp** [comment]
This is how I originally implemented the tests for the GRPC functionality, but I'm no Golang developer by any means so happy to have a second pair of eyes to improve them / modify them as needed: https://github.com/cmartell-at-ocp/jwt-middleware/pull/1/files#diff-bb6f1fede3f7c5aba7d6f2bc166273856fe965d7e1d5f49ee476ee7243cf4042

**Comment by agilezebra** [comment]
Thanks Carlos. 
I've made these changes https://github.com/Brainnwave/jwt-middleware/compare/04ddbae4a27ddb0b3a6c16613b84aeffb3b01f62...6534057e3a7c2d7c1c575f78d31711f2486042e4, merged and released [v1.1.14](https://github.com/Brainnwave/jwt-middleware/releases/tag/v1.1.14)
Changes summary:
1) make the tests a little more generic, allowing for other Headers in tests in future
2) checking that the request is allowed and disallowed through as appropriate, regardless of the returned status
3) Looking for the `application/grpc` header is handled case insensitively and with respect to token boundaries. Annoyingly I couldn't find this functionally exported by the standard library.
