### ISSUE TITLE
String aud support

### ISSUE THREAD

**Issue by majidakbaridh** [Brainnwave/jwt-middleware#4]
Hi,

Thank you for your great work!
Can I use this plugin for validating JWT token based on audience, `aud`, if it be in string format not a URL?

**Comment by agilezebra** [comment]
`aud` doesn't have to be a url, it can be any arbitrary string. [This test](https://github.com/Brainnwave/jwt-middleware/blob/e05bf6b120cb3f49a720be911636fdaa6fa74b9c/jwt_test.go#L96) tests for an `aud` of simply `test`. Please let me know if that resolves the issue.
