### ISSUE TITLE
Incorrect method of locating JWKS URL

### ISSUE THREAD

**Issue by RickyCook** [Brainnwave/jwt-middleware#6]
From logs, it seems that the JWKS URL is loaded from `{issuer}/.well-known/jwks.json`. However, this isn't necessarily the same across auth providers. For example keycloak provides keys at `{issuer}/protocol/openid-connect/certs`.

The [canonical spec-compliant](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig) way of locating the JWKS URL is to load `{issuer}/.well-known/openid-configuration` and use the `jwks_uri` key specified there.

For example:

- [Google](https://accounts.google.com/.well-known/openid-configuration) (issuer accounts.google.com) JWKS URI is https://www.googleapis.com/oauth2/v3/certs
- [Okta](https://developer.okta.com/docs/reference/api/oidc/) (issuer {name}.okta.com) JWKS URI is {issuer}/oauth2/v1/keys
- [GitHub Actions](https://token.actions.githubusercontent.com/.well-known/openid-configuration) (issuer token.actions.githubusercontent.com) JWKS URI is https://token.actions.githubusercontent.com/.well-known/jwks

**Comment by agilezebra** [comment]
Thanks Ricky. Agree. Will fold your changes in and fix up to make the tests pass (which they currently) don't as-in in the PR. I'll add a new PR here and close yours once it's all working. ETA Monday.

**Comment by agilezebra** [comment]
Release https://github.com/Brainnwave/jwt-middleware/releases/tag/v1.1.7 created from these changes plus tests in https://github.com/Brainnwave/jwt-middleware/commit/272ee138b05e50c0c9634d129a43a0c61afe877e
